# name: "Bug reports"
# title:
# description: Use Q&A if you cannot fill out the form
labels:
  - bug
# assignees:
#   - macropygia
body:
  - type: markdown
    attributes:
      value: ⚠ Please write in plain English. (Repository owner is not a native English speaker.) ※日本語可
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Do all of the following conditions apply?
      options:
        - label: Using the latest version of the package.
          required: true
        - label: All dependencies are the version specified in `peerDependencies`. (Or the bug is caused by the version of dependency.)
          required: true
        - label: The bug is due to the implementation of the package, not to a dependency.
          required: true
        - label: I will provide a minimal reproducible example.
          required: true
  - type: checkboxes
    id: category
    attributes:
      label: Category
      description: You may select more than one.
      options:
        - label: Components
        - label: API
        - label: Cache
        - label: Logic (other than above)
        - label: Output HTML
        - label: Output CSS
        - label: Data Adapters
        - label: Other
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What's the expected result?
      description: Describe what you expect to happen.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Write or link to minimal reproducible example
      description: Recommended to create a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) and link to it.
    validations:
      required: true
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to create a pull request for this issue.
