blank_issues_enabled: false
contact_links:
  - name: Start a discussion
    url: https://github.com/macropygia/astro-image-processor/discussions/new/choose
    about: Any questions or suggestions about features or behavior.
