name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  changesets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint:fix
      - run: pnpm run format
      - run: pnpm run typecheck
      - run: pnpm run test

      - id: changesets
        uses: changesets/action@v1
        with:
          title: '[ci] release'
          commit: '[ci] release'
          publish: pnpm exec changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - if: steps.changesets.outputs.published == 'true'
        run: |
          pnpm install
          pnpm run build
        working-directory: ./website
      - if: steps.changesets.outputs.published == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/dist
      - if: steps.changesets.outputs.published == 'true'
        uses: actions/deploy-pages@v4
