name: Publish Dry-run

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  publish_dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm run lint:fix
      - run: pnpm run format
      - run: pnpm run typecheck
      - run: pnpm run test
      - run: npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
